# Atividade 8 — Limpeza e preparação da base

## Objetivo

O objetivo desta etapa é realizar a limpeza e preparação da base Online Retail para que os dados possam ser utilizados no treinamento do primeiro modelo do projeto.

Foram analisados valores ausentes, registros duplicados, tipos de dados, cancelamentos e valores inválidos. As transformações foram realizadas de acordo com o diagnóstico da base e registradas com suas respectivas justificativas, impactos e riscos.

## 1. Importações

Nesta etapa são carregadas as bibliotecas utilizadas para leitura, manipulação e preparação dos dados.

In [1]:
# --- 1. IMPORTAÇÕES -----------------------------------------

import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

## 2. Carregamento da base

A base original Online Retail será carregada para o ambiente Python.

Uma cópia da base original é mantida em memória para permitir a comparação entre os dados antes e depois da limpeza. O arquivo original não será sobrescrito.

In [3]:
# --- 2. CARREGAMENTO ----------------------------------------

df = pd.read_excel("Online Retail.xlsx", engine="openpyxl")

# Mantém uma cópia da base original para comparação
df_original = df.copy()

print("Base carregada com sucesso!")
print("Dimensões iniciais:", df.shape)

Base carregada com sucesso!
Dimensões iniciais: (541909, 8)

## 3. Inspeção inicial

Antes da aplicação das transformações, foram verificadas as dimensões da base, os tipos das colunas, os valores ausentes e os registros duplicados.

Também foi verificada a existência de uma variável-alvo categórica. Como o projeto utiliza uma abordagem de recomendação e não possui uma variável-alvo categórica definida, a proporção de classes não se aplica nesta etapa.

In [4]:
# --- 3. INSPEÇÃO INICIAL ------------------------------------

print("Dimensões da base:")
print(df.shape)

print("\nTipos das colunas:")
print(df.dtypes)

print("\nValores ausentes por coluna:")
print(df.isnull().sum())

print("\nQuantidade de duplicatas:")
print(df.duplicated().sum())

print("\nProporção de classes da variável alvo:")
print("Não se aplica, pois o projeto não possui uma variável-alvo categórica.")

Dimensões da base:
(541909, 8)

Tipos das colunas:
InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

Valores ausentes por coluna:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

Quantidade de duplicatas:
5268

Proporção de classes da variável alvo:
Não se aplica, pois o projeto não possui uma variável-alvo categórica.

## 4. Tratamento de valores ausentes

A principal coluna com valores ausentes relevante para o projeto é CustomerID.

Como o objetivo é relacionar as compras ao histórico de cada cliente para posteriormente realizar recomendações personalizadas, registros sem CustomerID não podem ser associados corretamente a um consumidor.

Foi escolhida a remoção desses registros em vez do preenchimento, pois não seria adequado criar artificialmente uma identificação de cliente que não existe na base original.

A coluna Description possui uma pequena quantidade de valores ausentes. Esses registros não foram removidos nesta etapa, pois o StockCode continua disponível para identificação do produto. Caso Description seja utilizada diretamente no modelo, esse tratamento poderá ser reavaliado.

In [5]:
# --- 4. TRATAMENTO DE AUSENTES ------------------------------

linhas_antes = len(df)

# Remove somente registros sem identificação de cliente
df = df.dropna(subset=["CustomerID"]).copy()

linhas_depois = len(df)

print("Tratamento de CustomerID:")
print("Linhas antes:", linhas_antes)
print("Linhas depois:", linhas_depois)
print("Linhas removidas:", linhas_antes - linhas_depois)

print("\nValores ausentes restantes:")
print(df.isnull().sum())

Tratamento de CustomerID:
Linhas antes: 541909
Linhas depois: 406829
Linhas removidas: 135080

Valores ausentes restantes:
InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

## 5. Remoção de registros duplicados

Foram removidos os registros que apresentavam todas as informações exatamente iguais.

Essa transformação evita que o mesmo registro seja considerado mais de uma vez nas análises e no treinamento posterior.

A estratégia escolhida foi remover somente duplicatas exatas. Isso reduz o risco de remover registros diferentes que apenas possuem algumas informações em comum.

É importante destacar que InvoiceNo repetido não significa necessariamente duplicidade, pois uma mesma nota pode possuir vários produtos.

In [6]:
# --- 5. DUPLICIDADES ----------------------------------------

linhas_antes = len(df)

# Remove somente registros completamente iguais
df = df.drop_duplicates().copy()

linhas_depois = len(df)

print("Linhas antes:", linhas_antes)
print("Linhas depois:", linhas_depois)
print("Duplicatas removidas:", linhas_antes - linhas_depois)

Linhas antes: 406829
Linhas depois: 401604
Duplicatas removidas: 5225

## 6. Padronização de categorias

Nesta etapa não foi realizada uma padronização de categorias.

As colunas categóricas, como Country e StockCode, foram mantidas em seus valores originais para preservar as informações da base.

Uma padronização poderá ser realizada posteriormente caso seja identificada alguma inconsistência necessária para o modelo.

In [7]:
# --- 6. PADRONIZAÇÃO DE CATEGORIAS --------------------------

print("Padronização de categorias:")
print("Não foi realizada nesta etapa.")
print("Os valores originais foram preservados.")

Padronização de categorias:
Não foi realizada nesta etapa.
Os valores originais foram preservados.

## 7. Codificação de variáveis categóricas

Nesta etapa não foi realizada a codificação das variáveis categóricas.

A codificação será definida posteriormente de acordo com as variáveis que realmente forem utilizadas no modelo de recomendação.

Dessa forma, evita-se aplicar uma transformação antes da definição das variáveis finais da modelagem.

In [8]:
# --- 7. CODIFICAÇÃO -----------------------------------------

print("Codificação:")
print("Não foi realizada nesta etapa.")
print("A necessidade de codificação será avaliada na etapa de modelagem.")

Codificação:
Não foi realizada nesta etapa.
A necessidade de codificação será avaliada na etapa de modelagem.

## 8. Escalonamento

Nesta etapa não foi realizado escalonamento dos dados.

A necessidade de escala será avaliada posteriormente de acordo com o modelo e com as variáveis utilizadas.

Como nenhuma transformação de escala é necessária apenas para realizar a limpeza da base, o StandardScaler não foi ajustado nesta etapa.

In [9]:
# --- 8. ESCALA ----------------------------------------------

print("Escalonamento:")
print("Não foi realizado nesta etapa.")
print("A necessidade de escala será avaliada durante a preparação do modelo.")

Escalonamento:
Não foi realizado nesta etapa.
A necessidade de escala será avaliada durante a preparação do modelo.

## Tabela de decisões

| Transformação | Coluna | Motivo | Impacto | Risco |
|---|---|---|---|---|
| Remoção de duplicatas | Todas | Evitar registros repetidos | Redução de linhas | Possível remoção de repetições legítimas |
| Conversão de tipo | InvoiceDate | Trabalhar corretamente com datas | Nenhuma linha removida | Possíveis problemas com datas inválidas |
| Remoção de valores ausentes | CustomerID | Necessário para relacionar compras aos clientes | Redução de linhas | Perda de registros sem identificação |
| Remoção de cancelamentos | InvoiceNo | Manter compras válidas | Redução de linhas | Perda de informações sobre cancelamentos |
| Validação de valores | Quantity e UnitPrice | Remover valores inválidos para a análise | Redução de linhas | Perda de devoluções ou ajustes |

## 9. Correção do tipo da coluna InvoiceDate

A coluna InvoiceDate representa a data e o horário das compras, mas precisa estar no formato adequado para facilitar análises temporais.

Foi escolhida a conversão para o tipo datetime utilizando pd.to_datetime(), pois os valores da coluna são compatíveis com esse formato.

Essa transformação não remove linhas nem colunas.

In [10]:
# --- 9. CORREÇÃO DE InvoiceDate -----------------------------

print("Tipo antes:", df["InvoiceDate"].dtype)

df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

print("Tipo depois:", df["InvoiceDate"].dtype)

Tipo antes: datetime64[ns]
Tipo depois: datetime64[ns]

## 10. Remoção de cancelamentos

Foram removidos os registros cujo InvoiceNo começa com a letra C, padrão utilizado na base para identificar cancelamentos.

A transformação foi realizada porque, nesta etapa, o objetivo é trabalhar com compras válidas para identificar padrões de consumo e gerar recomendações.

A estratégia escolhida foi utilizar o próprio padrão existente no InvoiceNo.

O principal risco é perder informações que poderiam ser utilizadas em uma análise específica de cancelamentos ou devoluções.

In [11]:
# --- 10. REMOÇÃO DE CANCELAMENTOS ---------------------------

linhas_antes = len(df)

df = df[~df["InvoiceNo"].astype(str).str.startswith("C")].copy()

linhas_depois = len(df)

print("Linhas antes:", linhas_antes)
print("Linhas depois:", linhas_depois)
print("Cancelamentos removidos:", linhas_antes - linhas_depois)

Linhas antes: 401604
Linhas depois: 392732
Cancelamentos removidos: 8872

## 11. Validação de Quantity e UnitPrice

Foram removidos os registros que apresentavam Quantity menor ou igual a zero ou UnitPrice menor ou igual a zero.

Para esta etapa, o objetivo é trabalhar com compras válidas e valores positivos de quantidade e preço.

A estratégia escolhida foi manter somente registros com Quantity > 0 e UnitPrice > 0.

O principal risco é que alguns valores negativos podem representar devoluções ou ajustes legítimos. Esses registros foram removidos porque o foco desta base tratada é identificar padrões de compras realizadas.

In [12]:
# --- 11. VALIDAÇÃO DE QUANTITY E UNITPRICE ------------------

linhas_antes = len(df)

df = df[
    (df["Quantity"] > 0) &
    (df["UnitPrice"] > 0)
].copy()

linhas_depois = len(df)

print("Linhas antes:", linhas_antes)
print("Linhas depois:", linhas_depois)
print("Linhas removidas:", linhas_antes - linhas_depois)

Linhas antes: 392732
Linhas depois: 392692
Linhas removidas: 40

## 12. Verificação final

Após todas as transformações, a base será novamente verificada para confirmar suas dimensões, valores ausentes e duplicatas restantes.

Também será comparada a quantidade de linhas e colunas antes e depois do processo de limpeza.

In [13]:
# --- 12. VERIFICAÇÃO FINAL ----------------------------------

print("========== COMPARAÇÃO ANTES X DEPOIS ==========")

print("Linhas antes:", df_original.shape[0])
print("Linhas depois:", df.shape[0])

print("Colunas antes:", df_original.shape[1])
print("Colunas depois:", df.shape[1])

print("\n========== BASE FINAL ==========")

print("Dimensões finais:", df.shape)

print("\nValores ausentes restantes:")
print(df.isnull().sum())

print("\nDuplicatas restantes:")
print(df.duplicated().sum())

print("\nPrimeiras linhas:")
display(df.head())

========== COMPARAÇÃO ANTES X DEPOIS ==========
Linhas antes: 541909
Linhas depois: 392692
Colunas antes: 8
Colunas depois: 8

========== BASE FINAL ==========
Dimensões finais: (392692, 8)

Valores ausentes restantes:
InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

Duplicatas restantes:
0

Primeiras linhas:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

### 13. Tabela de decisões

| Transformação               | Coluna afetada        | Motivo                                                         | Impacto                                 | Risco                                           |
| --------------------------- | --------------------- | -------------------------------------------------------------- | --------------------------------------- | ----------------------------------------------- |
| Remoção de valores ausentes | CustomerID            | Necessário para relacionar compras aos clientes                | **541.909 → 406.829 linhas**            | Perda de registros sem identificação            |
| Remoção de duplicatas       | Todas                 | Evitar registros exatamente repetidos                          | **406.829 → 401.604 linhas**            | Possível remoção de repetições legítimas        |
| Padronização de categorias  | Country / StockCode   | Não foram identificadas transformações necessárias nesta etapa | **Nenhuma alteração**                   | Inconsistências futuras podem exigir tratamento |
| Codificação                 | Variáveis categóricas | Será definida conforme as variáveis do modelo                  | **Nenhuma alteração**                   | Necessidade de codificação posterior            |
| Escalonamento               | Variáveis numéricas   | Será avaliado conforme o modelo utilizado                      | **Nenhuma alteração**                   | Necessidade de escala posterior                 |
| Conversão de tipo           | InvoiceDate           | Permitir tratamento correto de datas                           | **Nenhuma alteração de linhas/colunas** | Problemas poderiam ocorrer com datas inválidas  |
| Remoção de cancelamentos    | InvoiceNo             | Trabalhar com compras válidas                                  | **401.604 → 392.732 linhas**            | Perda de informações sobre cancelamentos        |
| Validação de valores        | Quantity / UnitPrice  | Manter quantidade e preço positivos                            | **392.732 → 392.692 linhas**            | Perda de devoluções ou ajustes legítimos        |

## 14. Verificação de vazamento de dados (Data Leakage)

A limpeza realizada nesta etapa não utilizou transformações que aprendem parâmetros a partir dos dados, como imputação por mediana, escalonamento ou codificação ajustada à base inteira.

Portanto, nenhuma transformação desse tipo foi ajustada sobre a base completa antes da divisão entre treino e teste.

As transformações realizadas foram regras de limpeza, conversão de tipos, remoção de duplicatas, tratamento de valores ausentes, remoção de cancelamentos e validação de valores.

Também não devem ser utilizadas como features identificações que não representam características úteis para o modelo. Identificadores, como InvoiceNo e CustomerID, deverão ser tratados adequadamente na etapa de preparação das entradas do modelo.

Não foi identificada nesta base uma coluna que seja criada somente após o desfecho da recomendação e que deva permanecer como entrada do modelo.

Nas próximas etapas, caso sejam utilizadas técnicas que aprendam parâmetros, como escalonamento, imputação ou codificação, o ajuste deverá ser realizado somente nos dados de treinamento e posteriormente aplicado aos dados de teste.

## 15. Prontidão para o Encontro 9

A base passou pelas principais etapas de limpeza identificadas no diagnóstico e foi salva separadamente da base original.

Neste momento, a base está preparada para a próxima etapa do projeto.

Antes do treinamento do primeiro modelo, ainda será necessário definir as variáveis que serão utilizadas como entradas do modelo e realizar, caso necessário, a codificação ou o escalonamento dessas variáveis utilizando somente os dados de treinamento.

## 16. Salvamento da base tratada

A base original não será sobrescrita.

Após todas as transformações, a base tratada será salva em um novo arquivo chamado dados_tratados.csv.

In [14]:
# --- 16. SALVAMENTO -----------------------------------------

df.to_csv("dados_tratados.csv", index=False)

print("Base tratada salva com sucesso!")
print("Arquivo: dados_tratados.csv")
print("Dimensões:", df.shape)

Base tratada salva com sucesso!
Arquivo: dados_tratados.csv
Dimensões: (392692, 8)

In [15]:
# --- 17. VERIFICAÇÃO DO ARQUIVO -----------------------------

df_verificacao = pd.read_csv("dados_tratados.csv")

print("Arquivo carregado novamente com sucesso!")
print("Dimensões do arquivo salvo:", df_verificacao.shape)

display(df_verificacao.head())

Arquivo carregado novamente com sucesso!
Dimensões do arquivo salvo: (392692, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

## 18. Conclusão

A base Online Retail foi analisada, limpa e preparada para a próxima etapa do projeto.

Foram tratados os valores ausentes de CustomerID, removidas duplicatas, corrigido o tipo de InvoiceDate, removidos cancelamentos e validados os valores de Quantity e UnitPrice.

As transformações foram justificadas e registradas na tabela de decisões, incluindo seus impactos e riscos.

A quantidade de linhas e colunas antes e depois da limpeza foi registrada e a base tratada foi salva separadamente, mantendo o arquivo original preservado.

A base tratada foi carregada novamente ao final do notebook para confirmar que o arquivo foi salvo e pode ser utilizado nas próximas etapas.